version: '3.8'
services:
  servicedb:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  # pgadmin: # Для тестов
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4:7
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  client-backend:
    image: client:0.0.1
    build:
      context: api/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - servicedb
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://servicedb/schema
    restart: on-failure
    volumes:
       - backend-volume:/var/lib/backend/data
volumes:
  db-data:
  pgadmin-data:
  backend-volume: